export const NEW_PROMPT_OPTIONS = {
  identity: [
    'young urban Indian professional in smart casuals',
    'traditional South Indian elder with kind expression',
    'North Indian street vendor with warm smile',
    'modern Mumbai creative director with glasses',
    'Delhi university student with backpack and notebooks',
    'Bengal classical dancer in performance costume',
    'Rajasthani folk musician with traditional turban',
    'Hyderabadi tech worker with ID badge and laptop bag',
    'Sikh man with neatly tied turban and trimmed beard',
    'Gujarati artisan working with handloom textiles',
    'Kashmiri shepherd wrapped in warm pheran cloak',
    'Goan café owner in relaxed resort attire',
    'Kerala houseboat captain with traditional mundu',
    'Tamil Carnatic vocalist on concert stage',
    'Malayali kathakali performer in elaborate makeup',
    'Marathi theatre actor backstage in costume',
    'urban Indian college student hanging out with friends',
    'Indian bride in traditional red silk ensemble',
    'Indian groom in cream sherwani and stole',
    'Hijab-wearing professional with confident posture',
    'global fashion blogger documenting street style',
    'Tokyo-inspired city commuter with headphones',
    'Parisian art student carrying sketchbook and tote bag',
    'New York creative in monochrome streetwear',
    'Afro-futurist designer with bold patterned jacket',
    'Latin American street artist with paint-splattered clothes',
    'Nordic traveler in layered winter outerwear',
    'Middle Eastern café visitor enjoying evening breeze',
    'K-pop inspired performer with colorful hairstyle',
    'retro Bollywood star from golden era cinema',
    'Indian startup founder presenting on stage',
    'spiritual seeker meditating in simple cotton attire',
    'yoga instructor with calm focused presence',
    'classical painter working in sunlit studio',
    'street photographer with camera strap across chest',
    'wedding photographer directing a portrait session',
    'village school teacher holding chalk and notebook',
    'Indian grandmother in soft cotton saree',
    'Indian grandfather in kurta and waistcoat',
    'global business executive in tailored formalwear',
    'independent musician busking on city street',
    'travel blogger exploring historic alleyways',
    'museum curator in minimalist contemporary outfit',
    'fashion runway model in couture ensemble',
    'architect studying building facades on site visit',
    'chef in crisp jacket plating food carefully',
    'barista in apron making handcrafted coffee',
    'market flower seller arranging fresh marigolds',
    'IT professional working late in office cubicle',
    'local guide showing hidden corners of old city',
    'festival attendee wrapped in colorful ethnic wear',
    'monsoon traveler with raincoat and umbrella',
    'heritage enthusiast documenting old havelis',
    'minimalist urban dweller in neutral tones',
    'eco-conscious shopper carrying reusable cloth bag'
  ],

  details: [
    'warm brown eyes with gentle gaze',
    'deep expressive eyes with subtle eyeliner',
    'soft wavy hair loosely tied back',
    'long straight hair neatly braided down the back',
    'short curly hair with defined texture',
    'salt-and-pepper hair brushed back neatly',
    'carefully parted hair with natural volume',
    'traditional jasmine flowers woven into hair',
    'small bindi centered on forehead',
    'detailed henna mehndi patterns on hands',
    'intricate nose ring with delicate chain',
    'stack of colorful glass bangles on wrist',
    'oxidized silver jewelry with handcrafted details',
    'minimal gold jewelry with subtle shimmer',
    'light natural makeup with dewy finish',
    'bold kohl-lined eyes with confident expression',
    'freckles softly visible across cheeks',
    'slender elegant frame with graceful posture',
    'well proportioned full-figured hourglass silhouette',
    'strong athletic build with poised stance',
    'petite and delicate proportions with gentle gestures',
    'broad shoulders with relaxed posture',
    'gentle smile with slight dimples',
    'wide genuine laughter with closed eyes',
    'thoughtful gaze looking slightly away from camera',
    'focused eyes looking directly into lens',
    'folded hands in respectful namaste gesture',
    'hands gently holding a cup of chai',
    'fingers stained slightly with vibrant gulal colors',
    'soft dupatta draped gracefully over shoulders',
    'finely embroidered collar with tiny beads',
    'textured linen fabric with visible weave',
    'rich silk fabric with subtle sheen',
    'cotton khadi texture with handwoven irregularities',
    'traditional kolhapuri sandals on feet',
    'polished leather formal shoes',
    'white sneakers with clean minimal design',
    'delicate ankle bracelet with tiny bells',
    'classic wristwatch with leather strap',
    'round spectacles with thin metal frame',
    'thick black-rimmed glasses with modern design',
    'neatly trimmed beard and mustache',
    'clean-shaven jawline with sharp profile',
    'soft natural lighting highlighting cheekbones',
    'wind-swept hair adding motion',
    'raindrops visible on forehead and hair',
    'subtle forehead lines suggesting wisdom and experience',
    'cheeks slightly flushed with natural color',
    'neatly manicured nails with neutral polish',
    'traditional tilak mark on forehead',
    'turban folds carefully arranged with precision',
    'delicate scarf loosely wrapped around neck',
    'small hoop earrings catching highlights',
    'layered necklaces creating a statement look',
    'slight head tilt conveying curiosity'
  ],

  outfit: [
    'rich Banarasi silk saree with intricate zari border',
    'lightweight cotton saree with hand-block prints',
    'flowing pastel anarkali suit with subtle embroidery',
    'vibrant Punjabi patiala suit with phulkari dupatta',
    'chikankari kurta with white palazzo pants',
    'linen kurta paired with straight-cut trousers',
    'classic sherwani with embroidered collar and buttons',
    'bandhgala jacket with tailored churidar pants',
    'dhoti kurta with traditional angavastram drape',
    'elegant bridal lehenga with ornate handwork',
    'layered lehenga with mirror-work and tassels',
    'sharara suit with flared trousers and matching dupatta',
    'ghagra choli with bold Rajasthani patterns',
    'simple salwar kameez with printed dupatta',
    'Indo-western fusion dress with ethnic motifs',
    'cotton maxi dress with block-printed patterns',
    'well-fitted denim jacket over plain t-shirt',
    'oversized hoodie with relaxed joggers',
    'tailored navy business suit with crisp white shirt',
    'linen blazer with rolled-up sleeves and chinos',
    'streetwear hoodie with cargo pants and sneakers',
    'monochrome athleisure set with subtle branding',
    'bohemian layered skirt with embroidered blouse',
    'high-waisted wide-leg trousers with tucked-in shirt',
    'knee-length trench coat over minimalist outfit',
    'puffer jacket with knitted scarf and beanie',
    'safari-style shirt with multiple pockets and shorts',
    'simple kurta with jeans and leather sandals',
    'Nehru jacket layered over solid kurta',
    'embroidered waistcoat worn over plain shirt',
    'long shrug over basic tee and straight pants',
    'modest resort wear with flowing kaftan layers',
    'layered beachwear with light shawl and sunhat',
    'festival-ready outfit with colorful dupatta and juttis',
    'Himalayan woolen poncho with warm cap',
    'traditional mekhela chador with woven motifs',
    'Kasavu saree with golden border and simple blouse',
    'velvet evening gown with structured shoulders',
    'minimal slip dress layered with long cardigan',
    'plaid shirt with rolled sleeves and dark jeans',
    'vintage-inspired polka dot dress with belt',
    'retro Bollywood style kurta with flared sleeves',
    'office sari draped neatly with formal blouse',
    'kurti with cigarette pants and block heels',
    'printed jumpsuit with cinched waist',
    'simple black turtleneck with tailored trousers',
    'denim-on-denim coordinated set',
    'hooded raincoat over everyday clothes',
    'traditional lungi paired with casual shirt',
    'abaya with delicate embroidery along the edges',
    'hijab coordinated with long tunic and trousers',
    'chef jacket with apron and checkered trousers',
    'barista apron over casual shirt and jeans',
    'yoga wear set with breathable fabrics and soft tones',
    'floor-length cape over sleek evening outfit',
    'subtle sequin kurta for festive evening'
  ],

  setting: [
    'monsoon-soaked Mumbai street with neon signboards',
    'Hyderabad old city bazaar near historic arches',
    'narrow lanes of Varanasi ghats at sunrise',
    'Jaipur palace courtyard with pink sandstone walls',
    'Chennai Marina Beach with gentle evening waves',
    'Kolkata tram street lined with old colonial buildings',
    'Bangalore tech park with glass office towers',
    'Delhi India Gate boulevard at twilight',
    'quiet South Indian temple courtyard with stone pillars',
    'lush Kerala backwaters with traditional houseboats',
    'Rajasthani desert dunes under warm sunset sky',
    'Goan beach shack with colorful lanterns',
    'Himalayan hill station with misty pine trees',
    'small Indian village street with mud houses and banyan tree',
    'bustling local vegetable market with bright awnings',
    'modern Indian café with plants and wooden furniture',
    'rooftop terrace with city skyline and fairy lights',
    'old haveli with carved wooden doors and jharokhas',
    'art deco cinema hall with vintage posters',
    'suburban apartment balcony overlooking city lights',
    'metro station platform with arriving train',
    'university campus lawn with students relaxing',
    'narrow European cobblestone alleyway at dusk',
    'Tokyo-inspired neon city street in the rain',
    'New York skyline viewed from high rooftop',
    'Paris riverside promenade with glowing streetlamps',
    'Nordic lakeside cabin surrounded by pine forest',
    'Moroccan courtyard with patterned tiles and fountain',
    'Middle Eastern souk with hanging lamps and textiles',
    'minimalist art gallery with white walls and spotlights',
    'modern co-working space with glass partitions',
    'home office corner with laptop and plants',
    'cozy reading nook by large window with cushions',
    'train compartment with soft warm lighting',
    'airplane window seat view above the clouds',
    'city park with flowering trees and walking path',
    'heritage stepwell with geometric stone patterns',
    'riverfront promenade with food carts and benches',
    'narrow hillside road with hairpin bends',
    'tea plantation with workers among green rows',
    'ancient fort ramparts overlooking town below',
    'open-air amphitheater lit for performance',
    'indoor studio with seamless paper backdrop',
    'traditional courtyard house with central tree',
    'crowded festival ground with decorative lights',
    'rainy street reflecting colorful signboards',
    'tropical garden with lush foliage and soft pathways',
    'minimalist high-rise apartment interior',
    'local chai stall with metal kettles and stools',
    'food truck park with string lights at night',
    'yoga retreat center surrounded by nature',
    'bookstore with tall shelves and warm lamps',
    'metro skywalk with glass sides and commuters'
  ],

  timeOfDay: [
    'soft pre-dawn blue hour',
    'golden sunrise light just above horizon',
    'early morning with gentle haze',
    'late morning clear daylight',
    'harsh midday sun with crisp shadows',
    'soft overcast afternoon light',
    'monsoon afternoon with diffused grey sky',
    'late afternoon with long warm shadows',
    'classic golden hour before sunset',
    'fiery sunset with dramatic sky colors',
    'cool blue hour after sunset',
    'early evening with streetlights turning on',
    'nighttime under bright city lights',
    'quiet midnight with sparse lighting',
    'festival night filled with lanterns and fairy lights',
    'dusk with silhouettes against fading sky',
    'foggy early morning with low visibility',
    'starry rural night with minimal light pollution'
  ],

  mood: [
    'serene and introspective expression',
    'joyful and celebratory energy',
    'quietly confident and self-assured',
    'softly contemplative with distant gaze',
    'playful and lighthearted charm',
    'calm and grounded presence',
    'focused and determined look',
    'gentle kindness in the eyes',
    'subtle curiosity with raised eyebrow',
    'dreamy and slightly nostalgic',
    'peaceful contentment with faint smile',
    'lively excitement captured mid-laughter',
    'elegant poise with relaxed shoulders',
    'mysterious allure with half-shadowed face',
    'thoughtful seriousness without tension',
    'relaxed and easy-going demeanor',
    'celebratory festival joy with open smile',
    'reverent and respectful calm',
    'urban cool with understated attitude',
    'artistic intensity and concentration',
    'welcoming warmth with open body language',
    'shy charm with downcast eyes',
    'playfully teasing expression',
    'melancholic yet gentle mood',
    'hopeful optimism in the gaze',
    'soft romantic tenderness',
    'meditative stillness and inner peace',
    'energetic enthusiasm captured mid-gesture',
    'reflective mood looking out of a window',
    'poised like a classic painted portrait',
    'slightly surprised but pleasant reaction',
    'relieved and relaxed exhale',
    'proud and dignified bearing'
  ],

  pose: [
    'standing tall facing camera with relaxed shoulders',
    'standing at slight angle with hands in pockets',
    'walking toward camera with confident stride',
    'walking away while glancing back over shoulder',
    'seated cross-legged on floor in relaxed posture',
    'seated on steps with elbows resting on knees',
    'leaning against wall with one foot raised',
    'resting arms on balcony railing looking over city',
    'hands gently clasped in front of body',
    'one hand lightly touching chin in thoughtful pose',
    'arms crossed loosely with soft expression',
    'arms open mid-gesture as if explaining something',
    'looking down at object held in hands',
    'looking up toward sky with closed eyes',
    'half-turn profile pose with soft smile',
    'full profile pose emphasizing silhouette',
    'spinning slightly with fabric caught mid-twirl',
    'adjusting dupatta or scarf gracefully',
    'sitting on chair sideways with backrest as support',
    'perched on high stool with crossed legs',
    'leaning forward slightly toward camera',
    'leaning back slightly with relaxed posture',
    'hands resting gently on lap',
    'one hand placed lightly on heart',
    'stretching arms overhead in slow motion',
    'yoga tree pose with stable balance',
    'meditative seated pose with straight spine',
    'hands resting on table beside coffee cup',
    'reading a book held at chest height',
    'taking a photo with camera raised to eye',
    'checking phone while half-smiling',
    'holding umbrella while looking to the side',
    'lifting one side of long skirt slightly while walking',
    'sitting on window ledge looking outside'
  ],

  cameraAngle: [
    'eye-level 50mm portrait framing',
    'eye-level 85mm close-up portrait',
    'eye-level 35mm environmental portrait',
    'slightly above eye-level gentle flattering angle',
    'high-angle shot looking down on subject',
    'dramatic low-angle shot looking up at subject',
    'wide-angle 24mm street perspective',
    'ultra-wide 16mm dynamic city view',
    'telephoto 135mm compressed background portrait',
    'close-up crop focusing on face and shoulders',
    'extreme close-up focusing on eyes',
    'medium shot from waist up',
    'full-body shot with head-to-toe framing',
    'over-the-shoulder shot showing background scene',
    'three-quarter view capturing depth',
    'side profile shot against clean background',
    'back view shot with subject looking away',
    'dutch tilt angle for cinematic drama',
    'symmetric centered composition with leading lines',
    'rule-of-thirds framing with negative space',
    'framed through doorway or window',
    'shot through foreground foliage for depth',
    'reflection shot using mirror or glass',
    'top-down flat lay style angle',
    'low-angle shot from ground level',
    'close-up hands-only detail shot',
    'silhouette against bright background',
    'lens flare oriented toward camera',
    'shallow depth of field bokeh background',
    'deep focus with environment clearly visible',
    'portrait with softly blurred city lights behind',
    'wide establishing shot showing full setting',
    'tight crop on iconic accessory or prop'
  ],

  lighting: [
    'soft window light from one side',
    'warm golden hour rim-light on hair and shoulders',
    'backlit silhouette with gentle glow',
    'Rembrandt lighting with triangular cheek highlight',
    'loop lighting for flattering facial contours',
    'butterfly lighting from high frontal source',
    'split lighting creating dramatic half-shadowed face',
    'softbox lighting with smooth even skin tones',
    'large diffused overhead light for gentle shadows',
    'natural overcast daylight with low contrast',
    'harsh midday sun with defined shadows',
    'neon rim lighting with magenta and cyan tones',
    'cinematic upstage lighting with warm key and cool fill',
    'warm tungsten indoor lighting with cozy feel',
    'cool fluorescent-inspired lighting with subtle green tint',
    'soft warm lamp light focused on face',
    'string lights creating circular bokeh in background',
    'colored gel lighting with bold complementary hues',
    'dramatic low-key lighting with deep shadows',
    'bright high-key lighting with minimal shadows',
    'mixed lighting from streetlights and shop signs',
    'reflected light bounced from nearby wall',
    'sun rays streaming through window dust particles',
    'dappled light filtered through tree leaves',
    'monsoon cloudy light with soft muted colors',
    'festival night lighting with decorative lanterns',
    'spotlight focused on face with darker surroundings',
    'rim light outlining shoulders from behind',
    'underlit screen glow from phone or laptop',
    'soft candlelight flicker illuminating features',
    'sunset backlight with warm halo and lens flare',
    'cool moonlight effect with bluish tones',
    'studio beauty dish lighting for crisp highlights',
    'clamshell lighting with reflector under chin',
    'practical lights visible in frame adding depth',
    'LED panel light with subtle gradient on background',
    'cross lighting from two opposite sources',
    'side window light balanced with gentle fill',
    'soft gradient backdrop light behind subject',
    'reflections of colored signs on face in night scene',
    'shadow play on wall creating interesting shapes',
    'soft spotlight creating vignette around subject'
  ],

  style: [
    'realistic digital painting with fine brushwork',
    'semi-realistic illustration with soft shading',
    'flat vector illustration with bold shapes',
    'minimalist line art with clean contours',
    'watercolor wash with soft bleeding edges',
    'oil painting style with visible textured strokes',
    'impressionist style with broken color spots',
    'expressionist style with intense colors and forms',
    'comic book style with inked outlines and halftone dots',
    'anime-inspired cel shading with vibrant palettes',
    'manga-style black-and-white illustration',
    'children’s book illustration with friendly shapes',
    'vintage retro poster style with grainy texture',
    'mid-century modern illustration aesthetic',
    'Bollywood vintage film still look',
    'high-fashion editorial photography style',
    'street photography documentary style',
    'cinematic color grading with teal and orange tones',
    'noir-inspired monochrome with deep blacks',
    'soft pastel dreamlike aesthetic',
    'glitch art cyberpunk visual distortion',
    'futuristic holographic UI overlay style',
    'surrealist composition with unexpected juxtapositions',
    'fantasy concept art with dramatic scenery',
    'game concept art with detailed environments',
    '3D render with realistic global illumination',
    'low-poly 3D illustration style',
    'pixel art with limited color palette',
    'film grain look with subtle noise and scratches',
    'polaroid instant photo style with white border',
    'Kodachrome-style saturated film colors',
    'muted earth-tone editorial grading',
    'high-contrast black-and-white fine art style',
    'collage style with mixed paper textures',
    'hand-drawn sketch with visible pencil lines',
    'graphic novel style with bold paneling',
    'fashion illustration with elongated proportions',
    'architectural visualization render style',
    'Indian miniature painting inspired detailing',
    'Mughal painting inspired ornamental motifs',
    'Madhubani folk art inspired patterning',
    'Gond art inspired stylized forms',
    'contemporary Instagram-ready lifestyle aesthetic'
  ],

  era: [
    'Indus Valley civilization inspired setting',
    'ancient temple town ambience',
    'classical Gupta period artistic mood',
    'Mughal era royal court atmosphere',
    'Raj-era colonial India streetscape',
    'early 1900s Calcutta intellectual circles',
    '1920s jazz-age metropolitan vibe',
    '1940s wartime city backdrop',
    '1950s Bombay cinema golden age',
    '1960s psychedelic and experimental era',
    '1970s Bombay retro disco era',
    '1980s analog cassette and neon era',
    '1990s cable TV and early internet era',
    'early 2000s mall culture and tech boom',
    'contemporary 2020s global urban lifestyle',
    'near-future 2050 sustainable city vision',
    'distant cyberpunk-inspired future megacity',
    'alternate history steampunk-inspired world',
    'timeless mythological epic era',
    'heritage-inspired yet timeless modern fusion'
  ],

  props: [
    'string of fresh marigold garlands',
    'clay diyas with warm flickering flames',
    'brass puja thali with incense and flowers',
    'steel cup of steaming cutting chai',
    'earthen kulhad filled with hot chai',
    'filter coffee tumbler and davara set',
    'cloth bag filled with fresh vegetables',
    'stack of worn hardcover books',
    'open sketchbook with pencil drawings',
    'vinyl record player on wooden table',
    'old film camera hanging from neck',
    'modern mirrorless camera with prime lens',
    'smartphone with softly glowing screen',
    'laptop on desk with subtle screen light',
    'wired earphones casually hanging from pocket',
    'over-ear headphones resting around neck',
    'canvas backpack with travel patches',
    'roller suitcase standing beside subject',
    'folded newspaper tucked under arm',
    'colorful umbrella with raindrops on fabric',
    'handheld paper fan with printed pattern',
    'festive string lights hanging overhead',
    'hanging lanterns casting patterned shadows',
    'rangoli design on floor with bright powders',
    'flower petals scattered on pathway',
    'auto rickshaw parked in background',
    'classic scooter parked near doorway',
    'bicycle leaning against wall',
    'rickety wooden chair with worn paint',
    'low floor seating with cushions and rug',
    'wooden tabla and harmonium set',
    'sitar resting against wall',
    'microphone on stand in front of subject',
    'easel with half-finished painting',
    'palette with colorful acrylic paints',
    'pallet of stacked cardboard boxes',
    'street food cart with steaming pots',
    'stack of stainless steel tiffin carriers',
    'small potted plants on windowsill',
    'large tropical plant in ceramic pot',
    'framed artwork hanging on wall behind',
    'mirror with decorative frame reflecting scene',
    'calendar and notes pinned on corkboard',
    'fairy lights wrapped around balcony railing',
    'festival bunting flags overhead',
    'ludo board or carrom board on table',
    'tea kettle and glasses on tray',
    'street signboard in local language',
    'ticket stubs and travel passes on lanyard',
    'temple bells hanging from wooden beam',
    'incense smoke curling in the air'
  ]
};

export const NEW_GENDER_FEMALE_ONLY: string[] = [
  'Indian bride in traditional red silk ensemble',
  'Indian grandmother in soft cotton saree',
  'Hijab-wearing professional with confident posture',
  'elegant bridal lehenga with ornate handwork',
  'layered lehenga with mirror-work and tassels',
  'sharara suit with flared trousers and matching dupatta',
  'ghagra choli with bold Rajasthani patterns',
  'office sari draped neatly with formal blouse',
  'kurti with cigarette pants and block heels',
  'Kasavu saree with golden border and simple blouse'
];

export const NEW_GENDER_MALE_ONLY: string[] = [
  'Sikh man with neatly tied turban and trimmed beard',
  'Indian groom in cream sherwani and stole',
  'Indian grandfather in kurta and waistcoat',
  'Kashmiri shepherd wrapped in warm pheran cloak',
  'Kerala houseboat captain with traditional mundu',
  'classic sherwani with embroidered collar and buttons',
  'bandhgala jacket with tailored churidar pants',
  'dhoti kurta with traditional angavastram drape',
  'traditional lungi paired with casual shirt',
  'Nehru jacket layered over solid kurta',
  'neatly trimmed beard and mustache',
  'clean-shaven jawline with sharp profile'
];

export const NEW_VIBE_SETS: Record<string, string[]> = {
  cyberpunk: [
    'Tokyo-inspired neon city street in the rain',
    'monsoon-soaked Mumbai street with neon signboards',
    'neon rim lighting with magenta and cyan tones',
    'glitch art cyberpunk visual distortion',
    'cinematic color grading with teal and orange tones',
    'futuristic holographic UI overlay style',
    'wide-angle 24mm street perspective',
    'dutch tilt angle for cinematic drama',
    'reflection shot using mirror or glass',
    'nighttime under bright city lights',
    'underlit screen glow from phone or laptop'
  ],
  traditional_indian: [
    'rich Banarasi silk saree with intricate zari border',
    'lightweight cotton saree with hand-block prints',
    'flowing pastel anarkali suit with subtle embroidery',
    'ghagra choli with bold Rajasthani patterns',
    'dhoti kurta with traditional angavastram drape',
    'traditional mekhela chador with woven motifs',
    'Kasavu saree with golden border and simple blouse',
    'Jaipur palace courtyard with pink sandstone walls',
    'quiet South Indian temple courtyard with stone pillars',
    'heritage stepwell with geometric stone patterns',
    'string of fresh marigold garlands',
    'clay diyas with warm flickering flames',
    'rangoli design on floor with bright powders',
    'Indian miniature painting inspired detailing',
    'Madhubani folk art inspired patterning',
    'Mughal painting inspired ornamental motifs'
  ],
  modern_urban: [
    'young urban Indian professional in smart casuals',
    'Hyderabadi tech worker with ID badge and laptop bag',
    'Indian startup founder presenting on stage',
    'modern Indian café with plants and wooden furniture',
    'Bangalore tech park with glass office towers',
    'suburban apartment balcony overlooking city lights',
    'metro station platform with arriving train',
    'street photography documentary style',
    'monochrome athleisure set with subtle branding',
    'well-fitted denim jacket over plain t-shirt',
    'smartphone with softly glowing screen',
    'nighttime under bright city lights'
  ],
  dark_academia: [
    'museum curator in minimalist contemporary outfit',
    'bookstore with tall shelves and warm lamps',
    'stack of worn hardcover books',
    'warm tungsten indoor lighting with cozy feel',
    'noir-inspired monochrome with deep blacks',
    'high-contrast black-and-white fine art style',
    'plaid shirt with rolled sleeves and dark jeans',
    'cozy reading nook by large window with cushions',
    'reflection shot using mirror or glass',
    'serene and introspective expression'
  ],
  futuristic_scifi: [
    'distant cyberpunk-inspired future megacity',
    'near-future 2050 sustainable city vision',
    'futuristic holographic UI overlay style',
    '3D render with realistic global illumination',
    'low-poly 3D illustration style',
    'neon rim lighting with magenta and cyan tones',
    'cool moonlight effect with bluish tones',
    'telephoto 135mm compressed background portrait',
    'wide establishing shot showing full setting',
    'LED panel light with subtle gradient on background'
  ],
  vintage_nostalgia: [
    '1950s Bombay cinema golden age',
    '1970s Bombay retro disco era',
    '1980s analog cassette and neon era',
    'Bollywood vintage film still look',
    'vintage retro poster style with grainy texture',
    'film grain look with subtle noise and scratches',
    'polaroid instant photo style with white border',
    'old film camera hanging from neck',
    'vinyl record player on wooden table',
    'classic scooter parked near doorway',
    'string lights creating circular bokeh in background'
  ],
  bollywood_glamour: [
    'retro Bollywood star from golden era cinema',
    'Bollywood vintage film still look',
    'velvet evening gown with structured shoulders',
    'retro Bollywood style kurta with flared sleeves',
    'festival night filled with lanterns and fairy lights',
    'cinematic color grading with teal and orange tones',
    'spotlight focused on face with darker surroundings',
    'rim light outlining shoulders from behind',
    'three-quarter view capturing depth',
    'joyful and celebratory energy',
    'open-air amphitheater lit for performance'
  ],
  monsoon_romance: [
    'monsoon-soaked Mumbai street with neon signboards',
    'monsoon afternoon with diffused grey sky',
    'rainy street reflecting colorful signboards',
    'soft overcast afternoon light',
    'warm golden hour rim-light on hair and shoulders',
    'colorful umbrella with raindrops on fabric',
    'soft romantic tenderness',
    'walking toward camera with confident stride',
    'reflection shot using mirror or glass'
  ],
  spiritual_yoga_retreat: [
    'spiritual seeker meditating in simple cotton attire',
    'yoga instructor with calm focused presence',
    'yoga retreat center surrounded by nature',
    'meditative seated pose with straight spine',
    'yoga tree pose with stable balance',
    'soft window light from one side',
    'soft pastel dreamlike aesthetic',
    'muted earth-tone editorial grading',
    'serene and introspective expression',
    'tropical garden with lush foliage and soft pathways'
  ],
  royal_regal_india: [
    'Mughal era royal court atmosphere',
    'Jaipur palace courtyard with pink sandstone walls',
    'old haveli with carved wooden doors and jharokhas',
    'heritage stepwell with geometric stone patterns',
    'classic sherwani with embroidered collar and buttons',
    'bandhgala jacket with tailored churidar pants',
    'Indian miniature painting inspired detailing',
    'Mughal painting inspired ornamental motifs',
    'brass puja thali with incense and flowers',
    'temple bells hanging from wooden beam',
    'string of fresh marigold garlands'
  ],
  streetwear_global: [
    'New York creative in monochrome streetwear',
    'streetwear hoodie with cargo pants and sneakers',
    'well-fitted denim jacket over plain t-shirt',
    'denim-on-denim coordinated set',
    'wide-angle 24mm street perspective',
    'street photography documentary style',
    'urban cool with understated attitude',
    'metro station platform with arriving train',
    'smartphone with softly glowing screen',
    'over-ear headphones resting around neck'
  ],
  cozy_home_interiors: [
    'cozy reading nook by large window with cushions',
    'home office corner with laptop and plants',
    'small potted plants on windowsill',
    'large tropical plant in ceramic pot',
    'soft warm lamp light focused on face',
    'string lights creating circular bokeh in background',
    'tea kettle and glasses on tray',
    'minimalist high-rise apartment interior',
    'stack of worn hardcover books',
    'serene and introspective expression',
    'hands gently holding a cup of chai'
  ],
  desert_nomad: [
    'Rajasthani desert dunes under warm sunset sky',
    'small Indian village street with mud houses and banyan tree',
    'Himalayan hill station with misty pine trees',
    'safari-style shirt with multiple pockets and shorts',
    'Himalayan woolen poncho with warm cap',
    'wide establishing shot showing full setting',
    'late afternoon with long warm shadows',
    'dappled light filtered through tree leaves',
    'bicycle leaning against wall'
  ],
  art_gallery_minimalism: [
    'minimalist art gallery with white walls and spotlights',
    'museum curator in minimalist contemporary outfit',
    'minimalist line art with clean contours',
    'muted earth-tone editorial grading',
    'high-contrast black-and-white fine art style',
    'symmetric centered composition with leading lines',
    'rule-of-thirds framing with negative space',
    'framed artwork hanging on wall behind',
    'soft window light from one side',
    'quietly confident and self-assured'
  ]
};
